### Tarea Corta 05
## Fabian Vives

In [199]:
import torch as torch
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

### Pregunta 1

In [200]:
def verificar_propiedad_transpuesta(A, B):
    # Verificar que las matrices tienen la misma forma
    if A.shape != B.shape:
        return False
    
    # Calcular (A+B)^T
    suma = A + B
    suma_T = suma.T
    
    # Calcular A^T y B^T
    A_T = A.T
    B_T = B.T
    
    # Verificar que se cumple la propiedad
    return torch.allclose(suma_T, A_T + B_T)

In [201]:
A = torch.rand((4, 3))
print(A)
TA= torch.transpose(A,0,1)
print("Transpose A:", TA)
B = torch.rand((3, 4))
print(B)
TB= torch.transpose(B,0,1)
print("Transpose B:", TB)
print(verificar_propiedad_transpuesta(A, B))

tensor([[0.4986, 0.2578, 0.9991],
        [0.9883, 0.1229, 0.0947],
        [0.1210, 0.4976, 0.3725],
        [0.1727, 0.3207, 0.5945]])
Transpose A: tensor([[0.4986, 0.9883, 0.1210, 0.1727],
        [0.2578, 0.1229, 0.4976, 0.3207],
        [0.9991, 0.0947, 0.3725, 0.5945]])
tensor([[0.2388, 0.6108, 0.3853, 0.2577],
        [0.5687, 0.9111, 0.1620, 0.5232],
        [0.3156, 0.9907, 0.0256, 0.0207]])
Transpose B: tensor([[0.2388, 0.5687, 0.3156],
        [0.6108, 0.9111, 0.9907],
        [0.3853, 0.1620, 0.0256],
        [0.2577, 0.5232, 0.0207]])
False


### Pregunta 2

In [202]:
A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])
print(A)
# calcular el rango de A
print("Rango Completo", torch.linalg.matrix_rank(A))

tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
Rango Completo tensor(5)


In [203]:
A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [2. , 4. , 6., 8. , 10. ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [3. , 0 , 9., 0 ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

print("Rango 3")
print(A)
# calcular el rango de A
print("Rango de la matriz = ", torch.linalg.matrix_rank(A))

B = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [2. , 4. , 6., 8. , 10. ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [3. , 0 , 9., 0 ,0 ],
                   [2. , 0 , 6., 0 , 0 ]])

print("Rango 2")
print(B)
# calcular el rango de B
print("Rango de la matriz = ", torch.linalg.matrix_rank(B))

Rango 3
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 2.,  4.,  6.,  8., 10.],
        [ 1.,  0.,  3.,  0.,  0.],
        [ 3.,  0.,  9.,  0.,  0.],
        [ 1.,  0.,  2.,  0.,  6.]])
Rango de la matriz =  tensor(3)
Rango 2
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 2.,  4.,  6.,  8., 10.],
        [ 1.,  0.,  3.,  0.,  0.],
        [ 3.,  0.,  9.,  0.,  0.],
        [ 2.,  0.,  6.,  0.,  0.]])
Rango de la matriz =  tensor(2)


### Pregunta 3

Propiedad $\left(A^{T}A\right)^{+}A^{T}=A^{+}$

In [204]:
def verificar_inversa(A):
    print(A)

    """
    Verifica la propiedad inversa de una matriz usando la siguiente ecuación:
    (A^T * A)^-1 * A^T = A^-1
    Si la matriz no es invertible, la función devuelve False.
    """
    try:
        A_inv = np.linalg.inv(A)
        print("Inversa de A:\n", A_inv)
    except np.linalg.LinAlgError:
        print("Matriz A no invertible")
    
    # Calcula lado izquierdo
    AT = torch.transpose(A,0,1)
    print("Matriz transpuesta", AT )
    AM=torch.mm(AT,A)
    print("Matriz multiplicada por su transpuesta", AM)
    AMP = torch.pinverse(AM)
    print("Matriz pseudoinversa de la anterior", AMP)
    left = torch.mm(AMP,AT)
    print ("Lado izq",left)
    # Calcula lado derecho
    right = torch.pinverse(A) 
    print ("Lado der",right)
    
    #compare matriz 
    is_equal = torch.allclose( left, right,  atol=0.1)
    
    print("Son iguales los lados de la ecuación?\n", is_equal)
    return is_equal


# Pseudo inversa de una matriz singular

print("Pseudo inversa")
A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

verificar_inversa(A)

print("Pseudo inversa no invertible")
B = torch.tensor([ [1. , 2. ], [3. , 4. ] , [5. , 6.] ] )

verificar_inversa(B)

Pseudo inversa
tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
Inversa de A:
 [[ 18.     -9.     -2.    -18.    -15.   ]
 [  6.     -2.5    -1.     -6.     -5.   ]
 [ -6.      3.      1.      6.      5.   ]
 [ -1.5     0.625   0.25    1.75    1.25 ]
 [ -1.      0.5     0.      1.      1.   ]]
Matriz transpuesta tensor([[1., 0., 1., 0., 1.],
        [2., 2., 0., 1., 0.],
        [3., 2., 3., 0., 2.],
        [4., 0., 0., 4., 0.],
        [5., 0., 0., 0., 6.]])
Matriz multiplicada por su transpuesta tensor([[ 3.,  2.,  8.,  4., 11.],
        [ 2.,  9., 10., 12., 10.],
        [ 8., 10., 26., 12., 27.],
        [ 4., 12., 12., 32., 20.],
        [11., 10., 27., 20., 61.]])
Matriz pseudoinversa de la anterior tensor([[ 958.7859,  315.7592, -320.2628,  -83.4435,  -55.5455],
        [ 315.7589,  104.3354, -105.5866,  -27.5851,  -18.2650],
        [-320.2625, -105.5866,  107.0878,   27.8979,

True

### Pregunta 4

In [205]:
def es_simetrica_o_antisimetrica(A):
    
    # Verifica si una matriz es simétrica, antisimetrica o ninguna de las anteriores

    print(A)
    
    if (A.shape[0] == A.shape[1]):
        print("Matriz cuadrada")
    else:
        print("Matriz no cuadrada")
        return
    
    print("Transpuesta de matriz inicial")
    T = torch.transpose(A,0,1)
    print( T )
    
    if torch.equal( A, T):
        print ("Matriz es simetrica")
    elif torch.equal( A, -T):    
        print ("Matriz es antisimetrica")
    else:
        print ("Matriz no es antisimetrica ni simetrica")


A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

es_simetrica_o_antisimetrica(A)

B = torch.tensor([ [1. , 2. , 3. , 4. ], 
                   [0 , 2. , 2., 0  ], 
                   [1. , 0 , 3., 0  ],
                   [0 , 1. , 0, 4. ],
                   [1. , 0 , 2., 0  ]])

es_simetrica_o_antisimetrica(B)

C =  torch.tensor([ [0 , -5. ], [5., 0]])

es_simetrica_o_antisimetrica(C)

D =  torch.tensor([ [0 , 1 ], [1, 0]])

es_simetrica_o_antisimetrica(D)

tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
Matriz cuadrada
Transpuesta de matriz inicial
tensor([[1., 0., 1., 0., 1.],
        [2., 2., 0., 1., 0.],
        [3., 2., 3., 0., 2.],
        [4., 0., 0., 4., 0.],
        [5., 0., 0., 0., 6.]])
Matriz no es antisimetrica ni simetrica
tensor([[1., 2., 3., 4.],
        [0., 2., 2., 0.],
        [1., 0., 3., 0.],
        [0., 1., 0., 4.],
        [1., 0., 2., 0.]])
Matriz no cuadrada
tensor([[ 0., -5.],
        [ 5.,  0.]])
Matriz cuadrada
Transpuesta de matriz inicial
tensor([[ 0.,  5.],
        [-5.,  0.]])
Matriz es antisimetrica
tensor([[0, 1],
        [1, 0]])
Matriz cuadrada
Transpuesta de matriz inicial
tensor([[0, 1],
        [1, 0]])
Matriz es simetrica


In [206]:
def es_simetrica_o_antisimetrica(A):

    #Verifica si una matriz es simétrica, antisimetrica o ninguna de las anteriores
    
    print( A )
    
    if (A.shape[0] == A.shape[1]):
        print("Matriz cuadrada")
    else:
        print("Matriz no cuadrada")
        return
    
    print("Transpuesta")
    T = torch.transpose(A,0,1)
    print( T )
    
    if torch.equal( A, T):
        print ("Matriz es simetrica")
    elif torch.equal( A, -T):    
        print ("Matriz es antisimetrica")
    else:
        print ("Matriz no es antisimetrica ni simetrica")


A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

es_simetrica_o_antisimetrica(A+torch.transpose(A,0,1))

es_simetrica_o_antisimetrica(A-torch.transpose(A,0,1))

tensor([[ 2.,  2.,  4.,  4.,  6.],
        [ 2.,  4.,  2.,  1.,  0.],
        [ 4.,  2.,  6.,  0.,  2.],
        [ 4.,  1.,  0.,  8.,  0.],
        [ 6.,  0.,  2.,  0., 12.]])
Matriz cuadrada
Transpuesta
tensor([[ 2.,  2.,  4.,  4.,  6.],
        [ 2.,  4.,  2.,  1.,  0.],
        [ 4.,  2.,  6.,  0.,  2.],
        [ 4.,  1.,  0.,  8.,  0.],
        [ 6.,  0.,  2.,  0., 12.]])
Matriz es simetrica
tensor([[ 0.,  2.,  2.,  4.,  4.],
        [-2.,  0.,  2., -1.,  0.],
        [-2., -2.,  0.,  0., -2.],
        [-4.,  1.,  0.,  0.,  0.],
        [-4.,  0.,  2.,  0.,  0.]])
Matriz cuadrada
Transpuesta
tensor([[ 0., -2., -2., -4., -4.],
        [ 2.,  0., -2.,  1.,  0.],
        [ 2.,  2.,  0.,  0.,  2.],
        [ 4., -1.,  0.,  0.,  0.],
        [ 4.,  0., -2.,  0.,  0.]])
Matriz es antisimetrica
